import Head from "next/head"
import Link from "next/link"
import styles from "../styles/Home.module.css"

import NavBar from "../src/navBar"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <NavBar />
        <h1 className={styles.title}>Página principal</h1>
      </main>
    </div>
  )
}
