import { useState, useEffect } from "react"
import { useEntries } from "../lib/swr-hooks"
import styles from "../styles/Attendance.module.css"
export default function Attendance() {
  const [employees, setEmployees] = useState([])

  useEffect(() => {
    fetch("/api/getEmployees")
      .then((res) => res.json())
      .then((data) => setEmployees(data))
  }, [])

  console.log(employees)

  return (
    <div className={styles.tableContainer}>
      <table className={styles.mainTable}>
        <thead>
          <th className={styles.nameHeader}>Nombre</th>
          <th>Lu</th>
          <th>Ma</th>
          <th>Mi</th>
          <th>Ju</th>
          <th>Vi</th>
          <th>Sa</th>
          <th>Do</th>
          <th>Lu</th>
          <th>Ma</th>
          <th>Mi</th>
          <th>Ju</th>
          <th>Vi</th>
          <th>Sa</th>
          <th>Do</th>
          <th>Lu</th>
          <th>Ma</th>
          <th>Mi</th>
          <th>Ju</th>
          <th>Vi</th>
          <th>Sa</th>
          <th>Do</th>
          <th>Lu</th>
          <th>Ma</th>
          <th>Mi</th>
          <th>Ju</th>
          <th>Vi</th>
          <th>Sa</th>
          <th>Do</th>
        </thead>
        <tbody>
          <tr>
            <td>Gomez Cristian</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
          </tr>
          <tr>
            <td>Ramirez Claudio</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
          </tr>
          <tr>
            <td>Carrizo Alejandro</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
          </tr>
          <tr>
            <td>Roldan Juan</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
          </tr>
          <tr>
            <td>Duarte Matias</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
          </tr>
          <tr>
            <td>Gutierrez Alberto</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
          </tr>
          <tr>
            <td>Saccone Eva</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
          </tr>
          <tr>
            <td>Coronel Yanina</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
          </tr>
          <tr>
            <td>Morazan Daniel</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
          </tr>
          <tr>
            <td>Lucero Adrian</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
          </tr>
          <tr>
            <td>Gomez Cristian</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
          </tr>
          <tr>
            <td>Ramirez Claudio</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
          </tr>
          <tr>
            <td>Carrizo Alejandro</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
          </tr>
          <tr>
            <td>Roldan Juan</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
          </tr>
          <tr>
            <td>Duarte Matias</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
          </tr>
          <tr>
            <td>Gutierrez Alberto</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
            <td>V</td>
          </tr>
          <tr>
            <td>Saccone Eva</td>
          </tr>
          <tr>
            <td>Coronel Yanina</td>
          </tr>
          <tr>
            <td>Morazan Daniel</td>
          </tr>
          <tr>
            <td>Lucero Adrian</td>
          </tr>
          <tr>
            <td>Gomez Cristian</td>
          </tr>
          <tr>
            <td>Ramirez Claudio</td>
          </tr>
          <tr>
            <td>Carrizo Alejandro</td>
          </tr>
          <tr>
            <td>Roldan Juan</td>
          </tr>
          <tr>
            <td>Duarte Matias</td>
          </tr>
          <tr>
            <td>Gutierrez Alberto</td>
          </tr>
          <tr>
            <td>Saccone Eva</td>
          </tr>
          <tr>
            <td>Coronel Yanina</td>
          </tr>
          <tr>
            <td>Morazan Daniel</td>
          </tr>
          <tr>
            <td>Lucero Adrian</td>
          </tr>
          <tr>
            <td>Gomez Cristian</td>
          </tr>
          <tr>
            <td>Ramirez Claudio</td>
          </tr>
          <tr>
            <td>Carrizo Alejandro</td>
          </tr>
          <tr>
            <td>Roldan Juan</td>
          </tr>
          <tr>
            <td>Duarte Matias</td>
          </tr>
          <tr>
            <td>Gutierrez Alberto</td>
          </tr>
          <tr>
            <td>Saccone Eva</td>
          </tr>
          <tr>
            <td>Coronel Yanina</td>
          </tr>
          <tr>
            <td>Morazan Daniel</td>
          </tr>
          <tr>
            <td>Lucero Adrian</td>
          </tr>
        </tbody>
      </table>
    </div>
  )
}
